### ISSUE TITLE
[Back-Port Request - 1.19.3] For Mod: Mob-Death-Sounds

### ISSUE THREAD

**Issue by ExiledLizard** [Merphyx/Mob-Death-Sounds-Fabric-1.20.4#1]
Hey, @Merphyx, could you back-port the mod (name in title), to 1.19.3? Why 1.19.3? Because that is my main client, and I really seem to like your mod. Since 1.19.3 & 1.20.4 are very different, could you make the mod ONLY play a sound (minecraft:entity.experience_orb.pickup), at a default pitch (1), when a mob kill stat is increased? So like no commands or anything, so it could be easier for you, if you are ok with this request?

**Comment by Merphyx** [comment]
Done.

https://github.com/Merphyx/Mob-Death-Sounds-Fabric/releases/download/V1.0-1.19.3/mob-ds-v1.0+mc1.19.3.jar

**Comment by ExiledLizard** [comment]
@Merphyx, thank you so much! When I come back home, I'll download & run the mod, and let you know if any issues/crashes come up.

**Comment by ExiledLizard** [comment]
Hey, @Merphyx, I just came home, ran the mod, and I gotta say - the **mod works great**, no crashes or whatnots! Thank you so much for your time and effort.
